# Generated by Django 3.1.7 on 2022-05-09 15:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20220329_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='dateApproved',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 15, 19, 4, 966545, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='news',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 15, 19, 4, 966545, tzinfo=utc)),
        ),
    ]
