# Generated by Django 3.1.7 on 2022-05-09 16:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20220509_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='dateApproved',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 16, 8, 30, 781171, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='news',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 16, 8, 30, 781171, tzinfo=utc)),
        ),
    ]
