# Generated by Django 3.1.7 on 2022-05-15 04:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0005_auto_20220515_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='news',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 15, 4, 14, 47, 997615, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='news',
            name='lastModified',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 15, 4, 14, 47, 997615, tzinfo=utc)),
        ),
    ]
