# Generated by Django 3.1.7 on 2022-03-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthlySalary', models.FloatField()),
                ('housingRentAllowance', models.FloatField()),
                ('costOfLivingAllowance', models.FloatField()),
                ('transportationAllowance', models.FloatField()),
                ('bonus', models.FloatField()),
                ('overTimePayment', models.FloatField()),
                ('medicalInsurance', models.FloatField()),
                ('lifeInsurance', models.FloatField()),
            ],
            options={
                'db_table': 'calculator',
            },
        ),
    ]
