# Generated by Django 3.1.7 on 2022-03-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxinfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('maritalstatus', models.CharField(blank=True, db_column='maritalStatus', max_length=1, null=True)),
                ('taxableincome', models.IntegerField(blank=True, db_column='taxableIncome', null=True)),
                ('taxrate', models.IntegerField(blank=True, db_column='taxRate', null=True)),
            ],
            options={
                'db_table': 'taxinfo',
                'managed': False,
            },
        ),
    ]
